
services:
  postgres:
    image: postgres:15
    container_name: pyv_postgres
    environment:
      POSTGRES_DB: pyv_db
      POSTGRES_USER: pyv_user
      POSTGRES_PASSWORD: pyv_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyv-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pyv_db
      SPRING_DATASOURCE_USERNAME: pyv_user
      SPRING_DATASOURCE_PASSWORD: pyv_password
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - /root/.aws:/root/.aws:ro

volumes:
  postgres_data: