spring:
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml


  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true

s3:
  endpoint: https://storage.yandexcloud.net
  region: ru-central1
  bucket: pin-your-voice

jwt:
  secret: tk3EASATqPX1mxbMrOsoN4iAnZZl0pVQVeBtzG8t5tg=